// lab-8/photo-gallery-debutant/gallery-app/src/App.vue
<template>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container">
      <span class="navbar-brand">Gallery App - Lab 8</span>
      <button class="btn btn-outline-light btn-sm" @click="runAudit">Audit axe</button>
    </div>
  </nav>
  <main class="container py-4" aria-live="polite">
    <div class="alert alert-info">Article: Accessibilite dans les Micro-Frontends.</div>
    <div v-if="auditMessage" class="alert alert-success">{{ auditMessage }}</div>
    <div class="row g-4">
      <section class="col-md-4" aria-label="Liste des photos">
        <photo-list :selected-photo="selectedPhoto" @select-photo="selectPhoto" />
      </section>
      <section class="col-md-8" aria-label="Photo selectionnee">
        <photo-viewer :photo-id="selectedPhoto" />
      </section>
    </div>
    <section v-if="viewHistory.length > 0" class="mt-4" aria-label="Historique des consultations">
      <h2 class="h4">Historique des consultations</h2>
      <div class="table-responsive">
        <table class="table table-striped table-bordered align-middle mb-0">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Photo</th>
              <th scope="col">Badge</th>
              <th scope="col">Description</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(entry, index) in viewHistory" :key="entry.key">
              <th scope="row">{{ index + 1 }}</th>
              <td>{{ entry.title }}</td>
              <td>{{ entry.badge }}</td>
              <td>{{ entry.alt }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>
  </main>
</template>

<script setup>
import { defineAsyncComponent, ref } from 'vue';
import axe from 'axe-core';

const PhotoList = defineAsyncComponent(() => import('photoListApp/PhotoList'));
const PhotoViewer = defineAsyncComponent(() => import('photoViewerApp/PhotoViewer'));
const selectedPhoto = ref('1');
const auditMessage = ref('');
const viewHistory = ref([]);

const photos = {
  1: { id: '1', title: 'Architecture modulaire', badge: 'MFE', alt: 'Schema visuel representant trois modules frontend connectes.' },
  2: { id: '2', title: 'Composants accessibles', badge: 'ARIA', alt: 'Interface avec libelles et roles accessibles.' },
  3: { id: '3', title: 'Navigation clavier', badge: 'TAB', alt: 'Parcours clavier entre plusieurs boutons de galerie.' },
};

const selectPhoto = (photoId) => {
  selectedPhoto.value = photoId;
  const photo = photos[photoId] || photos[1];
  viewHistory.value = [
    ...viewHistory.value,
    { ...photo, key: `${photo.id}-${viewHistory.value.length + 1}` },
  ];
};

const runAudit = async () => {
  const result = await axe.run(document);
  auditMessage.value = `${result.violations.length} violation(s) detectee(s)`;
};
</script>

// lab-6/social-network-advanced/social-app/src/app.component.ts
import { CommonModule } from '@angular/common';
import { Component, Type, signal } from '@angular/core';

export const remoteNames = ['postListApp', 'profileApp'];

type PostHistoryEntry = {
  author: string;
  text: string;
};

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  template: `
    <nav class="navbar navbar-dark bg-secondary"><div class="container"><span class="navbar-brand">Social App Advanced - Lab 6</span><span class="badge text-bg-light">{{ selectedAuthor() }}</span></div></nav>
    <main class="container py-4">
      <div class="alert alert-info">Article: Tests dans les Micro-Frontends.</div>
      <div class="row g-4">
        <section class="col-md-8"><ng-container *ngIf="postList()" [ngComponentOutlet]="postList()"></ng-container></section>
        <section class="col-md-4"><ng-container *ngIf="profile()" [ngComponentOutlet]="profile()"></ng-container></section>
      </div>
      <section *ngIf="postHistory().length > 0" class="mt-4" aria-label="Historique des consultations">
        <h2 class="h4">Historique des consultations</h2>
        <div class="table-responsive">
          <table class="table table-striped table-bordered align-middle mb-0">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Auteur</th>
                <th scope="col">Publication</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let entry of postHistory(); let index = index">
                <th scope="row">{{ index + 1 }}</th>
                <td>{{ entry.author }}</td>
                <td>{{ entry.text }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>
    </main>
  `,
})
export class AppComponent {
  postList = signal<Type<unknown> | null>(null);
  profile = signal<Type<unknown> | null>(null);
  selectedAuthor = signal('Aucune selection');
  postHistory = signal<PostHistoryEntry[]>([]);

  constructor() {
    import('postListApp/PostList').then((m) => this.postList.set(m.PostListComponent));
    import('profileApp/Profile').then((m) => this.profile.set(m.ProfileComponent));
    window.addEventListener('social:post-selected', ((event: CustomEvent<{ author: string; text: string }>) => {
      const post = event.detail;

      this.selectedAuthor.set(post.author);
      this.postHistory.update((current) => [...current, post]);
    }) as EventListener);
  }
}
